#!/bin/bash

# Colors
RESET='\033[0m'
BLACK='\033[30m'
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
MAGENTA='\033[35m'
CYAN='\033[36m'
WHITE='\033[37m'

# Menu Colors:
A='\033[1;37m'
B='\033[0;37m'
C='\033[0;91m'
D='\033[0;32m'
O='\033[0;31m'
X=''

# Clean if exit is triggered
trap cleanup EXIT SIGHUP

# Trap interrupt code (^C ^Z)
trap '' SIGINT SIGTSTP

# Disable text printing
stty -echo

# Disable Ctrl+Z
stty susp ''

# Disable the cursor
tput civis

#============================ COMMON FUNCTIONS ================================#
# Cleanup function to delete the script
# And re-enable text printing and cursor
cleanup() {
    stty echo
    tput cnorm
	stty susp '^Z'
    rm -- "$0"
	clear
    printf "\n"
    printf "  $GREEN┌──────────────────────────────┐$RESET\n"
    printf "  $GREEN│ Cleaned everything. Goodbye! │$RESET\n"
    printf "  $GREEN└──────────────────────────────┘$RESET\n"
    printf "\n"
}

invalid_option() {
    printf "\n${RED}Invalid option '$choice'. Please try again.${RESET}\n"
	sleep 1
}

exit_script() {
    exit 0
}

void() {
	print ""
}
#==============================================================================#

#=========================== CORRECTION SUBMENU ===============================#
submenu_correction() {
    while true; do
        clear
        printf "\n"
        printf "  $O┌─$X────────────────────────────$X─┐$RESET\n"
        printf "  $O│ $A      Correction Menu       $O │$RESET\n"
        printf "  $O├─$X────────────────────────────$X─┤$RESET\n"
        printf "  $O│ $B 1. Get Mains               $O │$RESET\n"
        printf "  $O│ $B 2. Open Environment        $O │$RESET\n"
        printf "  $O│ $D 3. Go Back              (b)$O │$RESET\n"
        printf "  $O│ $C 4. Exit                 (q)$O │$RESET\n"
        printf "  $O└─$X────────────────────────────$X─┘$RESET\n"

        # Read user's option choice
        read -n 1 -r choice
        tput cub 1
        printf " "
        tput cub 1

        # Execute based on choice
        case $choice in
            1) get_mains ;;
            2) config_environment ;;
          b|3) break ;;
          q|4) exit_script ;;
            *) invalid_option ;;
        esac
    done
}

#============================== MAINS SUBMENU =================================#
get_libft_main() {
	curl -O https://raw.githubusercontent.com/Ugo-42/test_main/refs/heads/main/libft_main/HEHEHE.c
    printf "\n${GREEN}Libft Main Downloaded.${RESET}\n"
}

submenu_mains() {
    while true; do
        clear
        printf "\n"
        printf "  $O┌─$X────────────────────────────$X─┐$RESET\n"
        printf "  $O│ $A          My Mains          $O │$RESET\n"
        printf "  $O├─$X────────────────────────────$X─┤$RESET\n"
        printf "  $O│ $B 1. Libft                   $O │$RESET\n"
        printf "  $O│ $B 2.                         $O │$RESET\n"
        printf "  $O│ $D 3. Go Back              (b)$O │$RESET\n"
        printf "  $O│ $C 4. Exit                 (q)$O │$RESET\n"
        printf "  $O└─$X────────────────────────────$X─┘$RESET\n"

        # Read user's option choice
        read -n 1 -r choice
        tput cub 1
        printf " "
        tput cub 1

        # Execute based on choice
        case $choice in
            1) get_libft_main ;;
            2) void ;;
          b|3) break ;;
          q|4) exit_script ;;
            *) invalid_option ;;
        esac
    done
}
#==============================================================================#

#=============================== MAIN MENU ====================================#
while true; do
    clear
    printf "\n"
    printf "  $O┌─$X────────────────────────────$X─┐$RESET\n"
    printf "  $O│ $A        Main Menu           $O │$RESET\n"
    printf "  $O├─$X────────────────────────────$X─┤$RESET\n"
    printf "  $O│ $B 1. Correction              $O │$RESET\n"
    printf "  $O│ $B 2.                         $O │$RESET\n"
    printf "  $O│ $B 3.                         $O │$RESET\n"
    printf "  $O│ $C 4. Exit                 (q)$O │$RESET\n"
    printf "  $O└─$X────────────────────────────$X─┘$RESET\n"

    # Read user's option choice
    read -n 1 -r choice
    tput cub 1
    printf " "
    tput cub 1

    # Execute based on choice
    case $choice in
        1) submenu_correction ;;  # Call the submenu
        2) void ;;
        3) void ;;
      q|4) exit_script ;;
        *) invalid_option ;;
    esac
done
#==============================================================================#
